// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Profile struct {
	ID     int64
	UserID sql.NullInt64
	Name   string
	Bio    string
}

type User struct {
	ID       int64
	Email    string
	Password string
}
