// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID     int64
	UserID pgtype.Int8
	Name   string
	Bio    string
}

type User struct {
	ID       int64
	Email    string
	Password string
}
